### ISSUE TITLE
gzipped event files

### ISSUE THREAD

**Issue by derNarr** [quantling/pyndl#68] opened 2017-03-31 13:44 UTC
Make all event files gzipped with the internal gzip library and compression level 5 on default (around the best speed vs. size tradeoff).

Add to the documentation that these files can be viewed with zless and zcat...

**Comment by dekuenstle** [comment] 2017-04-02 10:28
Duplicate of #17? @derNarr

**Comment by derNarr** [comment] 2017-04-02 21:03
Partially, here it is more to save space on the hard drive. This is easy to do and might help according to speed as well. I would keep this one separate as it is easy to implement and clearly defined (in contrast to #17).

**Closed** 2017-05-09 05:17 UTC
Labels: documentation, enhancement
