### ISSUE TITLE
pip install broken

### ISSUE THREAD

**Issue by derNarr** [quantling/pyndl#106] opened 2017-08-12 06:29 UTC
Under miniconda with python 3.6.2 the pip install does not work. Probably something with the Cython install fails.

The install itself runs through without errors, but loading the packages fails with:

```
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from pyndl import ndl
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-eab04baf21a2> in <module>()
----> 1 from pyndl import ndl

~/miniconda3/lib/python3.6/site-packages/pyndl/ndl.py in <module>()
     19 from . import count
     20 from . import preprocess
---> 21 from . import ndl_parallel
     22
     23

ImportError: cannot import name 'ndl_parallel'

```

**Comment by derNarr** [comment] 2017-08-12 06:52
Workaround for now:

```
pip uninstall pyndl
git clone https://github.com/quantling/pyndl.git
cd pyndl
python setup.py develop
```

**Comment by Trybnetic** [comment] 2017-08-19 12:35
I get the same problem with 3.6.0 and 3.6.1 which is interesting as 3.6.1 was tested by travis. 3.5.4 works fine.

Probably some dependencies are broken?

When I have the time I will try to install the deps versions of the travis build and look whether this will work. 
We should probably re-run the last travis build and look whether this works.

If it is caused by the dependencies we should definitely fix the dependency versions (#90)

**Comment by dekuenstle** [comment] 2017-09-12 21:44
I don't run into this problem with normal cpython installation so it really seems to be related to miniconda.

**Comment by Trybnetic** [comment] 2017-12-05 13:48
@derNarr can you test this again?

I tried to replicate this error just a minute ago but had no problems anymore.

**Comment by Trybnetic** [comment] 2018-01-03 14:28
Seems like this issue was resolved by time

**Comment by mikecroucher** [comment] 2018-01-30 13:01
I've just had this exact error using miniconda on Linux.  Information about the environment follows:

```
conda list
# packages in environment at /home/fe1mpc/.conda/envs/ooominds:
#
certifi                   2016.2.28                py36_0  
Cython                    0.27.3                    <pip>
decorator                 4.1.2                    py36_0  
ipython                   6.1.0                    py36_0  
ipython_genutils          0.2.0                    py36_0  
jedi                      0.10.2                   py36_2  
netCDF4                   1.3.1                     <pip>
numpy                     1.14.0                    <pip>
openssl                   1.0.2l                        0  
pandas                    0.22.0                    <pip>
path.py                   10.3.1                   py36_0  
pexpect                   4.2.1                    py36_0  
pickleshare               0.7.4                    py36_0  
pip                       9.0.1                    py36_1  
prompt_toolkit            1.0.15                   py36_0  
ptyprocess                0.5.2                    py36_0  
pygments                  2.2.0                    py36_0  
pyndl                     0.4.0                     <pip>
python                    3.6.2                         0  
python-dateutil           2.6.1                     <pip>
pytz                      2017.3                    <pip>
readline                  6.2                           2  
setuptools                36.4.0                   py36_1  
simplegeneric             0.8.1                    py36_1  
six                       1.10.0                   py36_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
traitlets                 4.3.2                    py36_0  
wcwidth                   0.1.7                    py36_0  
wheel                     0.29.0                   py36_0  
xarray                    0.10.0                    <pip>
xz                        5.2.3                         0  
zlib                      1.2.11                        0  
```

**Comment by mikecroucher** [comment] 2018-01-30 13:10
I thought that maybe the problem was that some of the packages had been installed by pip (as a result of not having them available before I pip installed pyndl) so I tried again with a more pure conda environment.  Same error.

The new environment in which it failed is 
```
(ooominds_test) [fe1mpc@sharc-node144 scripts]$ conda list 
# packages in environment at /home/fe1mpc/.conda/envs/ooominds_test:
#
certifi                   2016.2.28                py36_0  
curl                      7.49.0                        1  
cython                    0.26                     py36_0  
decorator                 4.1.2                    py36_0  
hdf4                      4.2.12                        1  
hdf5                      1.8.17                        2  
ipython                   6.1.0                    py36_0  
ipython_genutils          0.2.0                    py36_0  
jedi                      0.10.2                   py36_2  
jpeg                      9b                            0  
libnetcdf                 4.4.1                         1  
mkl                       2017.0.3                      0  
netcdf4                   1.2.4               np113py36_0  
numpy                     1.13.1                   py36_0  
openssl                   1.0.2l                        0  
pandas                    0.20.3                   py36_0  
path.py                   10.3.1                   py36_0  
pexpect                   4.2.1                    py36_0  
pickleshare               0.7.4                    py36_0  
pip                       9.0.1                    py36_1  
prompt_toolkit            1.0.15                   py36_0  
ptyprocess                0.5.2                    py36_0  
pygments                  2.2.0                    py36_0  
pyndl                     0.4.0                     <pip>
python                    3.6.2                         0  
python-dateutil           2.6.1                    py36_0  
pytz                      2017.2                   py36_0  
readline                  6.2                           2  
setuptools                36.4.0                   py36_1  
simplegeneric             0.8.1                    py36_1  
six                       1.10.0                   py36_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
traitlets                 4.3.2                    py36_0  
wcwidth                   0.1.7                    py36_0  
wheel                     0.29.0                   py36_0  
xarray                    0.9.6                    py36_0  
xz                        5.2.3                         0  
zlib                      1.2.11                        0
```

**Comment by derNarr** [comment] 2018-01-31 18:01
# Standard ways do not work

```
conda create -n testpyndl
source activate testpyndl
conda install python
pip install pyndl
python -c 'from pyndl import ndl; print("success")'
conda env remove -n testpyndl
```
raises an error

```
conda create -n testpyndl2
source activate testpyndl2
git clone https://github.com/quantling/pyndl.git
pip install pyndl
python -c 'from pyndl import ndl; print("success")'
conda env remove -n testpyndl2
```
raises an error

# Development mode works

```
conda create -n testpyndl3
source activate testpyndl3
git clone https://github.com/quantling/pyndl.git
pip install -e pyndl/
python -c 'from pyndl import ndl; print("success")'
conda env remove -n testpyndl3
```
works fine

I am still investigating if there is a way to not use the binary distribution and still have cython code be compiled during installation.

**Comment by derNarr** [comment] 2018-02-06 16:28
The implicit use of cython with setuptools is build into setuptools since version 18.0 from Nov 2016.

https://github.com/douban/libmc/pull/45/files
https://stackoverflow.com/a/38057196

**Closed** 2018-02-07 10:16 UTC
Labels: bug

**Comment by mikecroucher** [comment] 2018-02-10 16:22
This fails on a Mac because clang

```
pip install pyndl
Collecting pyndl
  Using cached pyndl-0.4.1.tar.gz
Requirement already satisfied: numpy in ./miniconda3/envs/testing123/lib/python3.6/site-packages (from pyndl)
Requirement already satisfied: cython in ./miniconda3/envs/testing123/lib/python3.6/site-packages (from pyndl)
Requirement already satisfied: pandas in ./miniconda3/envs/testing123/lib/python3.6/site-packages (from pyndl)
Requirement already satisfied: xarray in ./miniconda3/envs/testing123/lib/python3.6/site-packages (from pyndl)
Requirement already satisfied: netCDF4 in ./miniconda3/envs/testing123/lib/python3.6/site-packages (from pyndl)
Requirement already satisfied: pip in ./miniconda3/envs/testing123/lib/python3.6/site-packages (from pyndl)
Requirement already satisfied: python-dateutil>=2 in ./miniconda3/envs/testing123/lib/python3.6/site-packages (from pandas->pyndl)
Requirement already satisfied: pytz>=2011k in ./miniconda3/envs/testing123/lib/python3.6/site-packages (from pandas->pyndl)
Requirement already satisfied: six>=1.5 in ./miniconda3/envs/testing123/lib/python3.6/site-packages (from python-dateutil>=2->pandas->pyndl)
Building wheels for collected packages: pyndl
  Running setup.py bdist_wheel for pyndl ... error
  Complete output from command /Users/walkingrandomly/miniconda3/envs/testing123/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/zq/wsjmzrv9655bw9fg5r93s8sm0000gn/T/pip-build-oyww403w/pyndl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/zq/wsjmzrv9655bw9fg5r93s8sm0000gn/T/tmpbfkl37ikpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.6
  creating build/lib.macosx-10.7-x86_64-3.6/pyndl
  copying pyndl/preprocess.py -> build/lib.macosx-10.7-x86_64-3.6/pyndl
  copying pyndl/ndl.py -> build/lib.macosx-10.7-x86_64-3.6/pyndl
  copying pyndl/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/pyndl
  copying pyndl/activation.py -> build/lib.macosx-10.7-x86_64-3.6/pyndl
  copying pyndl/count.py -> build/lib.macosx-10.7-x86_64-3.6/pyndl
  copying pyndl/corpus.py -> build/lib.macosx-10.7-x86_64-3.6/pyndl
  running build_ext
  skipping 'pyndl/ndl_parallel.c' Cython extension (up-to-date)
  building 'pyndl.ndl_parallel' extension
  creating build/temp.macosx-10.7-x86_64-3.6
  creating build/temp.macosx-10.7-x86_64-3.6/pyndl
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/walkingrandomly/miniconda3/envs/testing123/include -arch x86_64 -I/Users/walkingrandomly/miniconda3/envs/testing123/include -arch x86_64 -I/Users/walkingrandomly/miniconda3/envs/testing123/include/python3.6m -I/Users/walkingrandomly/miniconda3/envs/testing123/lib/python3.6/site-packages/numpy/core/include -c pyndl/ndl_parallel.c -o build/temp.macosx-10.7-x86_64-3.6/pyndl/ndl_parallel.o -fopenmp
  clang: error: unsupported option '-fopenmp'
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pyndl
  Running setup.py clean for pyndl
Failed to build pyndl
Installing collected packages: pyndl
  Running setup.py install for pyndl ... error
    Complete output from command /Users/walkingrandomly/miniconda3/envs/testing123/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/zq/wsjmzrv9655bw9fg5r93s8sm0000gn/T/pip-build-oyww403w/pyndl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/zq/wsjmzrv9655bw9fg5r93s8sm0000gn/T/pip-jhjzgm1l-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.6
    creating build/lib.macosx-10.7-x86_64-3.6/pyndl
    copying pyndl/preprocess.py -> build/lib.macosx-10.7-x86_64-3.6/pyndl
    copying pyndl/ndl.py -> build/lib.macosx-10.7-x86_64-3.6/pyndl
    copying pyndl/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/pyndl
    copying pyndl/activation.py -> build/lib.macosx-10.7-x86_64-3.6/pyndl
    copying pyndl/count.py -> build/lib.macosx-10.7-x86_64-3.6/pyndl
    copying pyndl/corpus.py -> build/lib.macosx-10.7-x86_64-3.6/pyndl
    running build_ext
    skipping 'pyndl/ndl_parallel.c' Cython extension (up-to-date)
    building 'pyndl.ndl_parallel' extension
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/pyndl
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/walkingrandomly/miniconda3/envs/testing123/include -arch x86_64 -I/Users/walkingrandomly/miniconda3/envs/testing123/include -arch x86_64 -I/Users/walkingrandomly/miniconda3/envs/testing123/include/python3.6m -I/Users/walkingrandomly/miniconda3/envs/testing123/lib/python3.6/site-packages/numpy/core/include -c pyndl/ndl_parallel.c -o build/temp.macosx-10.7-x86_64-3.6/pyndl/ndl_parallel.o -fopenmp
    clang: error: unsupported option '-fopenmp'
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Users/walkingrandomly/miniconda3/envs/testing123/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/zq/wsjmzrv9655bw9fg5r93s8sm0000gn/T/pip-build-oyww403w/pyndl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/zq/wsjmzrv9655bw9fg5r93s8sm0000gn/T/pip-jhjzgm1l-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/zq/wsjmzrv9655bw9fg5r93s8sm0000gn/T/pip-build-oyww403w/pyndl/
```
